export const STORE_ACTION_TYPES = {
  UPDATE_LANGUAGE: "UPDATE LANGUAGE",
  GET_LANGUAGE: "GET LANGUAGE",
  GET_CYCLES: "GET CYCLES",
  ADD_CYCLE: "ADD CYCLE",
  UPDATE_CYCLE: "UPDATE_CYCLE",
  DELETE_CYCLE: "DELETE_CYCLE",
  START_LOADING: "START LOADING",
  END_LOADING: "END LOADING",
};
